language: go

go:
  - 1.18.x
  - 1.19.x
  - 1.20.x
before_script:
  - GO_FILES=$(find . -iname '*.go' -type f | grep -v /vendor/)
  - go get golang.org/x/lint

script:
  - go test -v -race ./...
  - go vet ./...
  - golint -set_exit_status $(go list ./...)
